In [1]:
import torch as th
import numpy as np

In [2]:
tensor_a = th.tensor([1,2,3,4])
tensor_b = th.tensor([5,6,7,8])

In [3]:
print(tensor_a + tensor_b)
print(tensor_a.add(tensor_b))
print(th.add(tensor_a, tensor_b))

tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])
tensor([ 6,  8, 10, 12])


In [4]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [5]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [6]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [7]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [8]:
th.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [9]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [10]:
tensor_a

tensor([1, 2, 3, 4])

In [11]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [12]:
tensor_a

tensor([ 6,  8, 10, 12])

# Create a Simple Neural Network

In [13]:
import torch as th
import torch.nn as nn
import torch.nn.functional as F

In [15]:
# Create a model class that inherits nn.Module
class Model(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.fc1 = nn.Linear(in_features, 16)
        self.fc2 = nn.Linear(16,8)
        self.out = nn.Linear(8,out_features)
        
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.out(x)
        
        return x

In [17]:
# pick a manual seed for randomization
th.manual_seed(42)
model = Model(4, 3)